# Generated by Django 4.2.2 on 2023-07-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesignup',
            old_name='joiningdate',
            new_name='dob',
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='address',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='adhar',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='bank_acc',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='blood_grp',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='father_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='ifsc_code',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='mother_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='pan',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='employeesignup',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
