# Generated by Django 4.2.2 on 2023-08-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_rename_joiningdate_employeesignup_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesignup',
            name='img',
            field=models.ImageField(default='', upload_to='static/uploaded_images'),
        ),
    ]
