# Generated by Django 4.2.2 on 2023-08-14 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employeesignup_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesignup',
            name='img',
            field=models.ImageField(default='staic/images/account logo.png', upload_to='static/uploaded_images'),
        ),
    ]
