# Generated by Django 4.2.2 on 2023-08-14 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employeesignup_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesignup',
            name='img',
            field=models.ImageField(default='staic/uploaded_images/account logo.png', upload_to='static/uploaded_images'),
        ),
    ]
