# Generated by Django 4.2.2 on 2023-08-14 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeesignup_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesignup',
            name='img',
            field=models.FileField(default='media/account logo.png', null=True, upload_to=''),
        ),
    ]
