# Generated by Django 4.2.2 on 2023-08-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employeesignup_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeesignup',
            name='img',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
